### ISSUE TITLE
礼物消息重复打印

### ISSUE THREAD

**Issue by Yenightx** [saermart/DouyinLiveWebFetcher#1]
实测，观众只送一个礼物，但打印会输出两次
![image](https://github.com/saermart/DouyinLiveWebFetcher/assets/19188745/569f128f-ac00-4456-be40-0aa8adf0d616)

**Comment by saermart** [comment]
可以重写`self._parseGiftMsg`，解析出logId或giftId，去重后打印

**Comment by Yenightx** [comment]
改了_parseGiftMsg最后的输出

    trace_id = message.trace_id
    if trace_id not in self.traceId_list:
        self.traceId_list.insert(0, trace_id)
        print(f"【礼物msg】{user_name} 送出了 {gift_name}x{gift_cnt}")
    if len(self.traceId_list) > 1000:
        self.traceId_list.pop(-1)
