### ISSUE TITLE
现在还能抓取匿名的直播吗

### ISSUE THREAD

**Issue by NancyDHelms** [saermart/DouyinLiveWebFetcher#10]

**Comment by saermart** [comment]
可以抓到弹幕的呀

**Comment by saermart** [comment]
> 想抓匿名直播间的用户uid

这个目前没有好办法

**Comment by NancyDHelms** [comment]
返回的响应里面好像不存在sec_uid

**Comment by gaoming714** [comment]
您好，如果我是管理员可以登录进去查看到匿名背后的id信息的话，是否有方法。
换而言之我可以保存cookie，在一个登录的状态下尽心弹幕的提取，是否有方法在wss上增加这个登录状态呢？
