### ISSUE TITLE
WebSocket error

### ISSUE THREAD

**Issue by joseph16388** [saermart/DouyinLiveWebFetcher#13]
WebSocket connected.
WebSocket error:  Connection to remote host was lost.
WebSocket error:  DouyinLiveWebFetcher._wsOnClose() takes 2 positional arguments but 4 were given

**Comment by joseph16388** [comment]
id填错了

**Comment by 2640008009** [comment]
WebSocket error:  Connection to remote host was lost.
WebSocket error:  DouyinLiveWebFetcher._wsOnClose() takes 2 positional arguments but 4 were given同样的问题，为啥啊
