### ISSUE TITLE
WebSocket error:  empty or no certificate,

### ISSUE THREAD

**Issue by ielid** [saermart/DouyinLiveWebFetcher#14]
WebSocket error:  empty or no certificate, match_hostname needs a SSL socket or SSL context with either CERT_OPTIONAL or CERT_REQUIRED
大佬，报错 需要证书 请问您遇到过吗  如何解决的

**Comment by saermart** [comment]
这个问题没遇到过哦，可能跟你的业务代码逻辑有关系，刚测试了下代码是正常的
