### ISSUE TITLE
太棒了

### ISSUE THREAD

**Issue by scxxp** [saermart/DouyinLiveWebFetcher#16]
一次成功，希望能持续更新。

**Comment by ielid** [comment]
奇怪 我怎么不行啊，代码没变动。但是跑起来会提示
WebSocket error:  ("hostname 'webcast3-ws-web-lq.douyin.com' doesn't match either of '*.alicdn.com', '*.cmos.greencompute.org', 'cmos.greencompute.org', 'm.intl.taobao.com', '*.mobgslb.tbcache.com', 'alikunlun.com', '*.alikunlun.com', 's.tbcdn.cn', '*.django.t.taobao.com', 'alicdn.com'",)
WebSocket connection closed.

用的是python3.8

**Comment by scxxp** [comment]
> 奇怪 我怎么不行啊，代码没变动。但是跑起来会提示 WebSocket error: ("hostname 'webcast3-ws-web-lq.douyin.com' doesn't match either of '_.alicdn.com', '_.cmos.greencompute.org', 'cmos.greencompute.org', 'm.intl.taobao.com', '_.mobgslb.tbcache.com', 'alikunlun.com', '_.alikunlun.com', 's.tbcdn.cn', '*.django.t.taobao.com', 'alicdn.com'",) WebSocket connection closed.
> 
> 用的是python3.8

GPT说是你的SSL证书验证问题，我也不懂，我是小白
