### ISSUE TITLE
私密直播间

### ISSUE THREAD

**Issue by YUruohen** [saermart/DouyinLiveWebFetcher#2]
支持私密直播间吗？

**Comment by saermart** [comment]
目前还没测试，你可以试下再反馈回来哦

**Comment by YUruohen** [comment]
我看你是通过wss协议获取的消息，但是私密直播间是没返回用户信息那些的，只有一个11111的id

**Comment by saermart** [comment]
> 我看你是通过wss协议获取的消息，但是私密直播间是没返回用户信息那些的，只有一个11111的id

这个是直播间设置的，服务器根据直播间设置返回的数据就是这些的话，通过其他协议来解析直播间弹幕也无法获取到的

**Comment by YUruohen** [comment]
是的，我之前也是不能获取到私密直播间的，后面看到有视频有人可以获取到私密的，就是不明白这点是怎么做到的

**Comment by saermart** [comment]
> 是的，我之前也是不能获取到私密直播间的，后面看到有视频有人可以获取到私密的，就是不明白这点是怎么做到的

有链接吗，学习下

**Comment by YUruohen** [comment]
b站有
