### ISSUE TITLE
运行时老是报错啊，

### ISSUE THREAD

**Issue by 2640008009** [saermart/DouyinLiveWebFetcher#20]
老哥们，为什么有时候运行中会提示 WebSocket error: Connection to remote host was lost. WebSocket error: DouyinLiveWebFetcher._wsOnClose() takes 2 positional arguments but 4 were given，有人遇到这个问题没

**Comment by saermart** [comment]
代码是可运行的，你如果大规模请求或者嵌入到其他业务代码的话请自己考虑应用场景和业务逻辑哦。
