### ISSUE TITLE
大佬，有办法解决吗？商家账号直播间无法获取数据

### ISSUE THREAD

**Issue by molihuan** [saermart/DouyinLiveWebFetcher#21]
我的账号是商家账号,属于私密账号,未登录的用户爬取不到数据,
直接在没有登录抖音号的浏览器打开直播间链接显示：”服务器开小差了，点击刷新重试“
在已经登录抖音号的浏览器打开直播间正常显示：如下方的图片
![image](https://github.com/saermart/DouyinLiveWebFetcher/assets/78474077/18e0a86b-f75f-405e-b31f-2847574c942a)

**Comment by molihuan** [comment]
没事了，是我的设置有问题

**Comment by gaoming714** [comment]
> 没事了，是我的设置有问题

您好，请问您如何解决的，我现在登录后才能看到每个用户id，否则是带有*号的，但是我并不清楚如何登录。
