### ISSUE TITLE
爬不到弹幕的问题，我也在找解决办法，应该是要获取登录状态，然后拿去链接ws

### ISSUE THREAD

**Issue by ddGuo** [saermart/DouyinLiveWebFetcher#22]
之前我就提过了，被删除了。
很难得重现这个问题，重现条件是，当前电脑浏览器打开抖音直播，弹窗需要登录，这个时候，是爬取不到弹幕的。
为什么需要会弹窗登录呢？已知，这是一个直播公司，公司只有一个光猫，这个公司应该很多电脑打开了抖音直播，ip被和谐了？但是重启光猫了也没有用。并且这个公司其他电脑打开网页的抖音直播，都是强制弹窗 需要登录。
一般来说浏览器打开抖音直播，是不需要登录，就能看到右侧的弹幕信息，这也是爬虫实现的原理，因为目前的爬虫，都是不登录的。

**Comment by saermart** [comment]
有一个情况，太过频繁的使用某个 ip 去访问抖音接口会触发风控，轻度风控可能会要求你登录账户。

**Comment by AFatOtaku** [comment]
我这边是跑了几天WS开始没有消息  加上COOKIE就好了  不知道有没有不用COOKIE的方法

**Comment by gaoming714** [comment]
> 我这边是跑了几天WS开始没有消息 加上COOKIE就好了 不知道有没有不用COOKIE的方法

请问具体如何加cookie呢？我的场景中，无cookie的话没有信息，需要添加cookie

**Comment by AFatOtaku** [comment]
> > 我这边是跑了几天WS开始没有消息 加上COOKIE就好了 不知道有没有不用COOKIE的方法
> 
> 请问具体如何加cookie呢？我的场景中，无cookie的话没有信息，需要添加cookie

headers = {
                    "cookie": f"ttwid={self.ttwid};" + util.getCookie()【这里换成你的COOKIE或者对应方法】,
                    'user-agent': self.user_agent,
                }
...
...
...
async with self._session.ws_connect(self.wssUrl, 
                        receive_timeout=self._heartbeat_interval + 5,
                        headers= headers【cookie信息在header里面】
                ) as websocket:
