### ISSUE TITLE
大佬WebSocket error:  Connection to remote host was lost

### ISSUE THREAD

**Issue by 2640008009** [saermart/DouyinLiveWebFetcher#23]
WebSocket error:  Connection to remote host was lost.
WebSocket error:  DouyinLiveWebFetcher._wsOnClose() takes 2 positional arguments but 4 were given
代码没有任何改动，跑一会就这样了，多次运行都是这样

**Comment by littleStone-chan** [comment]
俺也一样，之前可以的，突然就不行了。

**Comment by saermart** [comment]
是不是被风控了

**Comment by 2640008009** [comment]
> 是不是被风控了

应该不是，在pc上运行是这样，手机上pydroid运行也是(开的数据)，

**Comment by littleStone-chan** [comment]
应该是直播没开，断开链接的报错没处理好

**Comment by 2640008009** [comment]
> 应该是直播没开，断开链接的报错没处理好

直播开着，我浏览器都没关
