### ISSUE TITLE
大神.WebSocket connected.WebSocket error: Connection to remote host was lost..

### ISSUE THREAD

**Issue by Adam34332** [saermart/DouyinLiveWebFetcher#25]
大神, 昨天抖音的爬取还可以用. 今天早上发现就变成了"INFO:websocket:Websocket connected
WebSocket connected.WebSocket error: Connection to remote host was lost.
ERROR:websocket:Connection to remote host was lost. - goodbye
ERROR:websocket:error from callback DouyinLiveWebFetcher._wsOnClose() missing 1 required positional argument: 'close_base'
WebSocket error: DouyinLiveWebFetcher._wsOnClose() missing 1 required positional argument: 'close_base'" B站我还私信了你. 
<img width="432" alt="微信图片_20240503140139" src="https://github.com/saermart/DouyinLiveWebFetcher/assets/137849982/f82923f7-bbe2-427a-9758-ee8fb2059aeb">
-.-改了些代码, 但是用另外一台电脑下载源项目也是这个反应, 也应该不是IP. 用了VPS转Tun模式也是一样. 就很迷, 昨天些代码还可以用. 今早起来发现连不到服务器了. 是我的问题还是项目?

**Comment by saermart** [comment]
这个应该是你那边的问题，我这里测试是可以的

**Comment by Adam34332** [comment]
> 这个应该是你那边的问题，我这里测试是可以的
谢谢回复啊, 昨天晚上写代码还是好的. 今天早上起来就出现这个情况. = =就很迷. 谢谢作者, 你觉得大概可能是什么情况?我看有其他人也提到过类似的问题.

**Comment by Adam34332** [comment]
> 这个应该是你那边的问题，我这里测试是可以的

找到原因了. 被封控了.

**Comment by 2640008009** [comment]
> > 这个应该是你那边的问题，我这里测试是可以的
> 
> 找到原因了. 被封控了.

怎么查到被封控了，封控的是谁的ip，后续咋解决呢
