### ISSUE TITLE
弹幕解析失败，渴求大佬尽快找到新方法

### ISSUE THREAD

**Issue by sj719** [saermart/DouyinLiveWebFetcher#31]

**Comment by sj719** [comment]
https://www.bilibili.com/video/BV1mM4m1k7ic/?spm_id_from=333.788&vd_source=39285cdc8caf0961060085314c21366b

前两天看视频，有没有可能和新增的a_bogus参数有关

**Comment by saermart** [comment]
我刚刚试了没有问题呀。。直播间 e.g ：[直播间链接](https://live.douyin.com/384022190328)

结果：
`
【进场msg】[96575489090][男]海上山杜鹃哥 进入了直播间
【直播间统计msg】8309在线观众
【点赞msg】雅致 点了10个赞
【聊天msg】[96046245699]小懒猫: 没人在我们小区干这事儿呢，我就不用做饭了
【聊天msg】[3908116048775528]梦梦💃: 有血糖高的。我有 办法
【进场msg】[3025462755857223][女]Xiaocao 进入了直播间
【进场msg】[111070945418][女]用户9877904936885 进入了直播间
【进场msg】[2703033489956235][女]用户8145469570266 进入了直播间
【统计msg】当前观看人数: 8503, 累计观看人数: 47.3万
【直播间统计msg】8284在线观众
【点赞msg】华 点了8个赞
【点赞msg】天长地久 点了3个赞
【聊天msg】[975966593891432]洪涛饭店: 多少钱一份
【进场msg】[548011580339755][女]用户2288352349311 进入了直播间
【进场msg】[2744858534492856][男]吉祥e 进入了直播间
【进场msg】[3043072093467709][男]有情有义 进入了直播间
【直播间统计msg】8261在线观众
【点赞msg】雅致 点了9个赞

`

**Comment by sj719** [comment]
感谢大佬
