### ISSUE TITLE
连接中断

### ISSUE THREAD

**Issue by Heigxaon** [saermart/DouyinLiveWebFetcher#34]
当直播间20秒没有任何动静的时候，会出现
WebSocket error:  Connection to remote host was lost.
WebSocket error:  DouyinLiveWebFetcher._wsOnClose() takes 2 positional arguments but 4 were given
程序就直接结束了，怎么解决

**Comment by saermart** [comment]
可以自己加个中断判断，然后再连接

**Comment by Heigxaon** [comment]
用心跳包搞定了

**Comment by hotdogarea** [comment]
> 用心跳包搞定了

问下大佬，使用心跳检测时，向抖音那边发送什么消息呢?频繁发送会引起封ip吗？
![image](https://github.com/saermart/DouyinLiveWebFetcher/assets/11146882/348ace07-c4e1-432e-ac4a-5faaa9f50fd1)

**Comment by hotdogarea** [comment]
> > 用心跳包搞定了
> 
> 问下大佬，使用心跳检测时，向抖音那边发送什么消息呢?频繁发送会引起封ip吗？ ![image](https://private-user-images.githubusercontent.com/11146882/337524455-348ace07-c4e1-432e-ac4a-5faaa9f50fd1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3MzgzMjIsIm5iZiI6MTcxNzczODAyMiwicGF0aCI6Ii8xMTE0Njg4Mi8zMzc1MjQ0NTUtMzQ4YWNlMDctYzRlMS00MzJlLWFjNGEtNWZhYWE5ZjUwZmQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDA1MjcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlMjU3NzhmZTJkMTQxNGI1ZmVmYzkyYTg4ZjVjODUyYmY4OGMwOTIxZWFjYjgyYWU1YmRlMTU0NjNhODM1OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KCv4Rdb5Cqqb2FJ4UBso52mFf-RmPmjINscdahNOEwk)

因为不管往服务器发任何消息，都是发送失败，这里不清楚抖音的心跳消息格式，有知道的大哥吗

**Comment by TerryYoung518** [comment]
> > > 用心跳包搞定了
> > 
> > 
> > 问下大佬，使用心跳检测时，向抖音那边发送什么消息呢?频繁发送会引起封ip吗？ ![image](https://private-user-images.githubusercontent.com/11146882/337524455-348ace07-c4e1-432e-ac4a-5faaa9f50fd1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3MzgzMjIsIm5iZiI6MTcxNzczODAyMiwicGF0aCI6Ii8xMTE0Njg4Mi8zMzc1MjQ0NTUtMzQ4YWNlMDctYzRlMS00MzJlLWFjNGEtNWZhYWE5ZjUwZmQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDA1MjcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlMjU3NzhmZTJkMTQxNGI1ZmVmYzkyYTg4ZjVjODUyYmY4OGMwOTIxZWFjYjgyYWU1YmRlMTU0NjNhODM1OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KCv4Rdb5Cqqb2FJ4UBso52mFf-RmPmjINscdahNOEwk)
> 
> 因为不管往服务器发任何消息，都是发送失败，这里不清楚抖音的心跳消息格式，有知道的大哥吗

心跳内容是字符串`hi`
