### ISSUE TITLE
WSS报错200

### ISSUE THREAD

**Issue by AFatOtaku** [saermart/DouyinLiveWebFetcher#40]
之前运行的挺正常的，但是今天突然就用不了了  WSS报错
不知道是账号被风控了  还是验证方法改了

以下是报错信息 

aiohttp.client_exceptions.WSServerHandshakeError: 200, message='Invalid response status', url=URL('wss://webcast3-ws-web-lq.douyin.com/webcast/im/push/v2/?app_name=douyin_web&version_code=180800&webcast_sdk_version=1.3.0&update_version_code=1.3.0&compress=gzip&internal_ext=internal_src:dim%7Cwss_push_room_id:7382522869470808883%7Cwss_push_did:7382522869470808883%7Cdim_log_id:202302171547011A160A7BAA76660E13ED%7Cfetch_time:1676620021641%7Cseq:1%7Cwss_info:0-1676620021641-0-0%7Cwrds_kvs:WebcastRoomStatsMessage-1676620020691146024_WebcastRoomRankMessage-1676619972726895075_AudienceGiftSyncData-1676619980834317696_HighlightContainerSyncData-2&cursor=t-1676620021641_r-1_d-1_u-1_h-1&host=https://live.douyin.com&aid=6383&live_id=1&did_rule=3&debug=false&endpoint=live_pc&support_wrds=1&im_path=/webcast/im/fetch/&user_unique_id=7382522869470808883&device_platform=web&cookie_enabled=true&screen_width=1440&screen_height=900&browser_language=zh&browser_platform=MacIntel&browser_name=Mozilla&browser_version=5.0%20(Macintosh;%20Intel%20Mac%20OS%20X%2010_15_7)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/110.0.0.0%20Safari/537.36&browser_online=true&tz_name=Asia/Shanghai&identity=audience&room_id=7382522869470808883&heartbeatDuration=0&signature=00000000')

**Comment by yuanchangchun** [comment]
可能是签名用的过多，被风控了吧。我也用不了

**Comment by hotdogarea** [comment]
一样的，有什么办法吗

**Comment by AFatOtaku** [comment]
目前我只能人工在开播的时候 去直播间把WSS获取下来  然后再这里用固定值
自动的签名计算方法没找出来

**Comment by yefeng2renxing** [comment]
接口更新了，错误签名值是会被服务器返回200，需要逆向signature的值，我试了一下逆向构造，没有成功

**Comment by saermart** [comment]
已更新
