### ISSUE TITLE
wss链接失效了

### ISSUE THREAD

**Issue by hellosqi** [saermart/DouyinLiveWebFetcher#45]

**Comment by iOSwang** [comment]
WebSocket error:  Handshake status 200 OK -+-+- 
WebSocket error:  DouyinLiveWebFetcher._wsOnClose() takes 2 positional arguments but 4 were given

**Comment by Bennna12** [comment]
在liveMan.py找到_wsOnClose，加多一个参数*args

**Comment by iOSwang** [comment]
> 在liveMan.py找到_wsOnClose，加多一个参数*args

WebSocket error:  Handshake status 200 OK 
WebSocket connection closed.

**Comment by iOSwang** [comment]
> > 在liveMan.py找到_wsOnClose，加多一个参数*args
> 
> WebSocket error: Handshake status 200 OK WebSocket connection closed.

不太行

**Comment by Bennna12** [comment]
哈哈，我也知道，所以我现在也在解决这个问题，感觉还是要破解js里的signature的生成方式

**Comment by SoYoungxSoWhat** [comment]
WebSocket error:  Handshake status 200 OK -+-+- 
WebSocket error:  _wsOnClose() takes 2 positional arguments but 4 were given

**Comment by hellosqi** [comment]
signature谁有

**Comment by sdrz001** [comment]
不行呢 求更新

**Comment by sdrz001** [comment]
https://blog.csdn.net/m0_75268677/article/details/137596255 谁看下这个 有没有大佬能看懂

**Comment by weizhi9586** [comment]
楼主求更新，哈哈

**Comment by iOSwang** [comment]
https://github.com/tiangalon/dy_danmaku_java 这个兄弟直接用Js生成的sign,有没有会写python的兄弟打个包，运行一个js，生成一下签名，最好把widnows跟mac,都给生成一下

**Comment by sdrz001** [comment]
问题是不会 啊  要是会弄的话就好了

**Comment by iOSwang** [comment]
windows直接在把sign那段代码抄过去，就好了，Mac还在打包那个js代码，擦

**Comment by sdrz001** [comment]
sign那段代码抄过去 能详细的说说吗

**Comment by iOSwang** [comment]
> sign那段代码抄过去 能详细的说说吗

他不是编译的有.exe么？你直接在启动你的python代码之前，把本地执行一下.exe拿到输出的sign，给你的python赋值就好了吧

**Comment by iOSwang** [comment]
<img width="1010" alt="image" src="https://github.com/user-attachments/assets/8caa1b15-dacf-4776-8a92-14838c05932d">
这事java代码里的，就这段换成python

**Comment by sdrz001** [comment]
好的哈 谢谢了 我去研究研究

**Comment by iOSwang** [comment]
> 好的哈 谢谢了 我去研究研究

客气了，他这个代码就是运行了命令行，传递了两个参数，用python的话，应该很简单，就是苹果电脑打包这个exe搞得我想吐

**Comment by sdrz001** [comment]
折腾了一晚上还是 失败了，貌似需要 user_unique_id？ 你成功了吗

**Comment by sdrz001** [comment]
import subprocess
import os

def sign(room_id, user_unique_id):
    # 构建命令行参数
    exe_path = os.path.join(os.path.dirname(__file__), 'protobuf\Signature.exe')
    command = [exe_path, room_id, user_unique_id]

    # 执行命令并获取输出
    try:
        process = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        output, error = process.communicate()
        if process.returncode == 0:
            # 如果程序正常结束，读取输出并返回
            signature = output.decode('utf-8').strip()
            return signature
        else:
            # 如果程序异常结束，打印错误信息
            print(f"Error executing Signature.exe: {error.decode('utf-8')}")
    except Exception as e:
        print(f"An exception occurred: {e}")

    return ""

# 测试函数
if __name__ == "__main__":
    room_id = "12345"
    user_unique_id = "abcdefg"
    signature = sign(room_id, user_unique_id)
    print(f"The signature is: {signature}")

**Comment by sdrz001** [comment]
感谢
iOSwang  搞定了哈

**Comment by saermart** [comment]
已更新
