### ISSUE TITLE
好像最近又跑不动了

### ISSUE THREAD

**Issue by weizhi9586** [saermart/DouyinLiveWebFetcher#46]
WebSocket error:  Handshake status 200 OK -+-+- {'server': 'volc-dcdn', 'content-length': '0', 'connection': 'keep-alive', 'date': 'Fri, 12 Jul 2024 07:35:48 GMT', 'handshake-msg': 'DEVICE_BLOCKED', 'handshake-status': '415', 'server-timing': 'inner; dur=52, cdn-cache;desc=MISS, origin;dur=149, edge;dur=0', 'x-tt-trace-host': '015f3ca947c964de55f9c7f9afccd8b7ec0708188bd3a93f77d1839f4321259bbec690b4fadfc54b2660e681112654d0806f1f2e1c56b9742eb9a7497f8a48c5ea6e8c46f02b493f80c5bc58d85385d5cc6288e4b453ebebd70848b4ebcd4c4ac0', 'x-tt-trace-tag': 'id=5', 'x-tt-trace-id': '00-a5dea10203010d10215c71a9d0b518ef-a5dea10203010d10-01', 'x-tt-logid': '20240712153548F12E4865E84EFB2CBAB4', 'via': 'n180-097-246-148.jsxzct02-container.Creative', 'x-request-ip': '14.154.11.222', 'x-dsa-trace-id': '172076974807628c31eac450ad0aab39c16b5c737a', 'x-dsa-origin-status': '200'} -+-+- b''

**Comment by lettergod** [comment]
把“好像”两个字去掉。

**Comment by saermart** [comment]
已更新。
