### ISSUE TITLE
有知道弹幕飘屏怎么获取吗？

### ISSUE THREAD

**Issue by xhr2** [saermart/DouyinLiveWebFetcher#48]
def _parseChatMsg(self, payload):
      '''聊天消息'''
      message = ChatMessage().parse(payload)
      user_name = message.user.nick_name
      user_id = message.user.id
      content = message.content

content 好像没有弹幕飘屏的数据
有没有大佬指点一下

**Comment by sdrz001** [comment]
你解决了签名的问题了吗

**Comment by saermart** [comment]
今天会更新。。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年07月16日 21:41 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | Re: [saermart/DouyinLiveWebFetcher] 有知道弹幕飘屏怎么获取吗？ (Issue #48) |

你解决了签名的问题了吗

**Comment by xhr2** [comment]
> 你解决了签名的问题了吗

签名问题不是最简单的吗，github都有现成的
https://github.com/jwwsjlm/douyinLive
