### ISSUE TITLE
还是要signature 啊

### ISSUE THREAD

**Issue by lmq886** [saermart/DouyinLiveWebFetcher#49]
WebSocket error:  Handshake status 200 OK -+-+- {'server': 'volc-dcdn', 'content-length': '0', 'connection': 'keep-alive', 'date': 'Tue, 16 Jul 2024 02:37:54 GMT', 'handshake-msg': 'DEVICE_BLOCKED', 'handshake-status': '415', 'server-timing': 'inner; dur=82, cdn-cache;desc=MISS,  origin;dur=152, edge;dur=16,  cdn-cache;desc=MISS', 'x-tt-trace-host': '015322e150330143e811c6e384c1c52d3dabf2fe1edb92ad4f76973fb1dec99c5c91addba49c26ec48c2485fb4f0a8d6adb01d2bc568bc5ecc087fa687e58d4e9af654b43c86d22e91654d588ee924b1d9d3fede0328cfca54ec5feb21d8650142747b5ed983671a8166cb0328bd2eb7236cb12f1a6ee5598f085e720da7ed1acf', 'x-tt-trace-tag': 'id=5', 'x-tt-trace-id': '00-b967537f03010f813ad52b5ae44c18ef-b967537f03010f81-01', 'x-tt-logid': '2024071610375450081B126C82623DFC5F', 'via': 'n157-149-136.whmp.Creative,n113-219-164-185.czct02-container.Creative', 'x-request-ip': '171.83.32.190', 'x-dsa-trace-id': '1721097474652c809ec71a6178d1e7ecfc743ae947', 'x-dsa-origin-status': '200'} -+-+- b''
WebSocket closed. <websocket._app.WebSocketApp object at 0x000001C31533F560>    
直接复制的地址可以用 拼接后signature的值要对应，修改就无法访问了 如何获取signature值呢

**Comment by saermart** [comment]
已更新
