### ISSUE TITLE
为什么我的user id总时为“111111”

### ISSUE THREAD

**Issue by sunmingqi-1** [saermart/DouyinLiveWebFetcher#5]
![image](https://github.com/saermart/DouyinLiveWebFetcher/assets/79261103/910a2c7a-9371-40bf-a67c-73dba733e854)

**Comment by saermart** [comment]
> ![image](https://github.com/saermart/DouyinLiveWebFetcher/assets/79261103/910a2c7a-9371-40bf-a67c-73dba733e854)
> 

因为这个直播间的主播设置了直播间不可见用户
