### ISSUE TITLE
下载最新代码，好像还是会报错

### ISSUE THREAD

**Issue by weizhi9586** [saermart/DouyinLiveWebFetcher#51]
大佬，下载了最新的代码，之前报js的问题，都做了相应包的升级。但是运行的时候，还是会出现以下问题
![1721190576222](https://github.com/user-attachments/assets/70125327-5d23-46ee-b708-eac11e19d238)

**Comment by saermart** [comment]
我这完全正常哇。。。

**Comment by weizhi9586** [comment]
搞定了，大佬，是我nodejs版本过高，降低到18点就能跑了，感谢！！
