### ISSUE TITLE
执行报错，看起来是js执行的时候没能正常执行。

### ISSUE THREAD

**Issue by braveappleliu** [saermart/DouyinLiveWebFetcher#52]
![image](https://github.com/user-attachments/assets/15ce274f-8e3a-46a7-865e-d3776d98ae62)

**Comment by weizhi9586** [comment]
你更新一下电脑noded的版本

**Comment by braveappleliu** [comment]
> 你更新一下电脑noded的版本

多谢，我试一下。

**Comment by braveappleliu** [comment]
> 你更新一下电脑noded的版本

已经更新了，版本是node的20.15.0 这个版本。 下载地址 https://nodejs.cn/download/
是运行的时候，要指定node的目录吗？

**Comment by weizhi9586** [comment]
不用啊，系统会找的，你重新运行下代码

**Comment by weizhi9586** [comment]
你是手动下载的吗，我是用电脑终端，npm下载的

**Comment by saermart** [comment]
我的NodeJs版本v18.2.0

**Comment by braveappleliu** [comment]
> 多谢，重启pycharm之后，可以了， 但又报错 zh 和 utf8的问题，按照代码注释中的提示， 也解决了。 但是又出现 ![image](https://private-user-images.githubusercontent.com/170919620/349406771-8f871de9-b03f-4504-b6e2-4706bf8f5eb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMDI0MzMsIm5iZiI6MTcyMTIwMjEzMywicGF0aCI6Ii8xNzA5MTk2MjAvMzQ5NDA2NzcxLThmODcxZGU5LWIwM2YtNDUwNC1iNmUyLTQ3MDZiZjhmNWViNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxN1QwNzQyMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NzlhOWM0ZmQzZTNhOTg5OWMxY2MxMTYyYjZkYmRjYjhhMTk0Nzg1OTk2OWJlMmIwODEzMDU0MWU5ZjhlODczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eb6iOGWpWNCMm6PnJUuW3QQuL32G4wdwelZMiNmzVRQ) 安装了jsdom之后， 还是不行， 安装是通过npm安装的。

看起来需要安装node 18.*.*的版本，我先试一下。

**Comment by SoYoungxSoWhat** [comment]
我跟你同样的问题报错语法错误，我用的pycharm社区版本，不能指定nodejs版本。然后我换windows命令行直接执行可以了。第一次用nodejs，npm install jsdom网不行，搜了下换阿里镜像秒装。现在跑起来了。


我看着ai说pycharm高级版好像支持我这里暂时没测试。
以下是文心一言的回答=========================================================

在PyCharm中指定Node.js的版本，可以通过以下步骤完成：

安装Node.js：首先，确保您已经在计算机上安装了所需版本的Node.js。您可以从Node.js官方网站下载并安装1234。
打开PyCharm设置：在PyCharm中，点击菜单栏中的“File” > “Settings”（对于Mac用户，是“PyCharm” > “Preferences”）24。
配置Node.js：在弹出的设置窗口中，选择“Languages & Frameworks” > “Node.js and NPM”124。
指定Node.js路径：在“Node Interpreter”字段中，点击右侧的“…”按钮，然后浏览并选择您已安装的Node.js的路径。这个路径通常指向Node.js的安装目录下的“node”可执行文件124。
保存并应用更改：确认设置无误后，点击“OK”保存配置1。

**Comment by braveappleliu** [comment]
> 我跟你同样的问题报错语法错误，我用的pycharm社区版本，不能指定nodejs版本。然后我换windows命令行直接执行可以了。第一次用nodejs，npm install jsdom网不行，搜了下换阿里镜像秒装。现在跑起来了。
> 
> 我看着ai说pycharm高级版好像支持我这里暂时没测试。 以下是文心一言的回答=========================================================
> 
> 在PyCharm中指定Node.js的版本，可以通过以下步骤完成：
> 
> 安装Node.js：首先，确保您已经在计算机上安装了所需版本的Node.js。您可以从Node.js官方网站下载并安装1234。 打开PyCharm设置：在PyCharm中，点击菜单栏中的“File” > “Settings”（对于Mac用户，是“PyCharm” > “Preferences”）24。 配置Node.js：在弹出的设置窗口中，选择“Languages & Frameworks” > “Node.js and NPM”124。 指定Node.js路径：在“Node Interpreter”字段中，点击右侧的“…”按钮，然后浏览并选择您已安装的Node.js的路径。这个路径通常指向Node.js的安装目录下的“node”可执行文件124。 保存并应用更改：确认设置无误后，点击“OK”保存配置1。

我用命令行执行，也还是报同样的错误， 找不到jsdom， 命令行也很简单， python main.py

**Comment by braveappleliu** [comment]
> > 我跟你同样的问题报错语法错误，我用的pycharm社区版本，不能指定nodejs版本。然后我换windows命令行直接执行可以了。第一次用nodejs，npm install jsdom网不行，搜了下换阿里镜像秒装。现在跑起来了。
> > 我看着ai说pycharm高级版好像支持我这里暂时没测试。 以下是文心一言的回答=========================================================
> > 在PyCharm中指定Node.js的版本，可以通过以下步骤完成：
> > 安装Node.js：首先，确保您已经在计算机上安装了所需版本的Node.js。您可以从Node.js官方网站下载并安装1234。 打开PyCharm设置：在PyCharm中，点击菜单栏中的“File” > “Settings”（对于Mac用户，是“PyCharm” > “Preferences”）24。 配置Node.js：在弹出的设置窗口中，选择“Languages & Frameworks” > “Node.js and NPM”124。 指定Node.js路径：在“Node Interpreter”字段中，点击右侧的“…”按钮，然后浏览并选择您已安装的Node.js的路径。这个路径通常指向Node.js的安装目录下的“node”可执行文件124。 保存并应用更改：确认设置无误后，点击“OK”保存配置1。
> 
> 我用命令行执行，也还是报同样的错误， 找不到jsdom， 命令行也很简单， python main.py

跑起来了，应该还是jsdom没有安装好。 安装jsdom的时候， 用的
npm config set registry https://mirrors.cloud.tencent.com/npm/
npm install jsdom --no-fund

安装的时候看到下面信息就说明安装好了。 
added 42 packages in 12s

最终看到

**Comment by saermart** [comment]
找不到js模块的一般都是自己node问题，可以卸载重装

**Comment by G-G-b-o-y** [comment]
可以参考[https://[github.com](https://github.com/)/](https://blog.csdn.net/xc_zhou/article/details/139099756)，我跟你一样的问题，装完jsdom之后重启电脑就解决了。
