### ISSUE TITLE
gbk编码问题如何修改

### ISSUE THREAD

**Issue by isZonghao** [saermart/DouyinLiveWebFetcher#53]
![QQ图片20240718175841](https://github.com/user-attachments/assets/fb1a7b83-6a6e-4e5e-9be1-97acf6b964f5)

看注释中有提示说这么改
  python模块subprocess的Popen类的__init__函数参数encoding值为 "utf-8"

但我对subprocess模块并不熟悉，具体要怎么改呢，大佬请赐教

**Comment by saermart** [comment]
就是修改它的源码，你可以找到 Python 的 subprocess.py 文件进行修改

**Comment by saermart** [comment]
点击报错信息里面那个文件链接，就可以直接找到（狗头）

**Comment by SXCSSYLJ** [comment]
![}NJTWXK4 (PWONAECAXTN](https://github.com/user-attachments/assets/8c6b82b5-c035-4307-82ed-209528aa397b)
修改了之后，我这个现在报utf未定义，怎么解决啊，请教一下

**Comment by isZonghao** [comment]
> ![}NJTWXK4 (PWONAECAXTN](https://private-user-images.githubusercontent.com/155440985/349931399-8c6b82b5-c035-4307-82ed-209528aa397b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMDEyNzcsIm5iZiI6MTcyMTMwMDk3NywicGF0aCI6Ii8xNTU0NDA5ODUvMzQ5OTMxMzk5LThjNmI4MmI1LWMwMzUtNDMwNy04MmVkLTIwOTUyOGFhMzk3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQxMTA5MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YmEzY2FjZGEyYTk0NzNmNTdlMWZiZjU5NzBhZTM5ZGYzZjIzZGNkODdjMDZiMjdjMDk3ODdiODk4YzlmY2IwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9ypyk-eki3SETREoU_pxo5ap3w46670uM1CAwtpzmJk) 修改了之后，我这个现在报utf未定义，怎么解决啊，请教一下

看报错明显是你把utf-8写错成了utf了吧

**Comment by isZonghao** [comment]
> ![}NJTWXK4 (PWONAECAXTN](https://private-user-images.githubusercontent.com/155440985/349931399-8c6b82b5-c035-4307-82ed-209528aa397b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMDEyNzcsIm5iZiI6MTcyMTMwMDk3NywicGF0aCI6Ii8xNTU0NDA5ODUvMzQ5OTMxMzk5LThjNmI4MmI1LWMwMzUtNDMwNy04MmVkLTIwOTUyOGFhMzk3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQxMTA5MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YmEzY2FjZGEyYTk0NzNmNTdlMWZiZjU5NzBhZTM5ZGYzZjIzZGNkODdjMDZiMjdjMDk3ODdiODk4YzlmY2IwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9ypyk-eki3SETREoU_pxo5ap3w46670uM1CAwtpzmJk) 修改了之后，我这个现在报utf未定义，怎么解决啊，请教一下

看报错明显是你把utf-8写错成了utf了吧

**Comment by SXCSSYLJ** [comment]
![E(ZPU12YFL 3V(@R 01P@C](https://github.com/user-attachments/assets/faebf19f-d74c-4f92-a0be-c64aa31f7004)
那不至于，现在不知道怎么解决

**Comment by isZonghao** [comment]
> ![E(ZPU12YFL 3V(@R 01P@C](https://private-user-images.githubusercontent.com/155440985/349933720-faebf19f-d74c-4f92-a0be-c64aa31f7004.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMDE4MjYsIm5iZiI6MTcyMTMwMTUyNiwicGF0aCI6Ii8xNTU0NDA5ODUvMzQ5OTMzNzIwLWZhZWJmMTlmLWQ3NGMtNGY5Mi1hMGJlLWM2NGFhMzFmNzAwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQxMTE4NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zN2E5MzZjODRiM2RhZWFhNmFhMmEzM2JhNTdiY2FlNGY0YjZhMGEwYTg1YTMyZDg3NmE0MzAxOTVlODcxOTIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.z39OEGVECWxznBkXd6hokYiQEUhoh6ulWDMFWO7u9Ps) 那不至于，现在不知道怎么解决

你没加双引号啊

**Comment by isZonghao** [comment]
> 点击报错信息里面那个文件链接，就可以直接找到（狗头）

大佬 我现在启动不报错了，但是运行起来报WebSocket的错，报完错链接就断了
![QQ图片20240718175841](https://github.com/user-attachments/assets/b620baff-2198-412a-b1e5-a379a8158f6b)

**Comment by SXCSSYLJ** [comment]
> > ![E(ZPU12YFL 3V(@R 01P@C](https://private-user-images.githubusercontent.com/155440985/349933720-faebf19f-d74c-4f92-a0be-c64aa31f7004.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMDE4MjYsIm5iZiI6MTcyMTMwMTUyNiwicGF0aCI6Ii8xNTU0NDA5ODUvMzQ5OTMzNzIwLWZhZWJmMTlmLWQ3NGMtNGY5Mi1hMGJlLWM2NGFhMzFmNzAwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQxMTE4NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zN2E5MzZjODRiM2RhZWFhNmFhMmEzM2JhNTdiY2FlNGY0YjZhMGEwYTg1YTMyZDg3NmE0MzAxOTVlODcxOTIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.z39OEGVECWxznBkXd6hokYiQEUhoh6ulWDMFWO7u9Ps) 那不至于，现在不知道怎么解决
> 
> 你没加双引号啊

好的好的我的解决了，自学的，基础比较弱，感谢感谢【抱拳】

**Comment by saermart** [comment]
> > 点击报错信息里面那个文件链接，就可以直接找到（狗头）
> 
> 大佬 我现在启动不报错了，但是运行起来报WebSocket的错，报完错链接就断了
> ![QQ图片20240718175841](https://github.com/user-attachments/assets/b620baff-2198-412a-b1e5-a379a8158f6b)
> 

nodejs 版本不对吧，应该是 v18.x 的

**Comment by isZonghao** [comment]
> > > 点击报错信息里面那个文件链接，就可以直接找到（狗头）
> > 
> > 
> > 大佬 我现在启动不报错了，但是运行起来报WebSocket的错，报完错链接就断了
> > ![QQ图片20240718175841](https://private-user-images.githubusercontent.com/33242403/349936540-b620baff-2198-412a-b1e5-a379a8158f6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMTEyMTAsIm5iZiI6MTcyMTMxMDkxMCwicGF0aCI6Ii8zMzI0MjQwMy8zNDk5MzY1NDAtYjYyMGJhZmYtMjE5OC00MTJhLWIxZTUtYTM3OWE4MTU4ZjZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDEzNTUxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0Njk0NmYxNjM5NzNhNTZmYWFhMjNmMDNlNTRhYmMwZWI0NjljZmI5Y2I1YjkzNjRiZTEyZTkzYzZlMjkxYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LXsGXqZ0NyvhMl1B0uS-8x7kOBi0LqeRcx5I4Moe3N8)
> 
> nodejs 版本不对吧，应该是 v18.x 的

哇 大佬 一眼就看出问题所在了，换成了18版本 确实可以了

**Comment by xyl123124** [comment]
改subprocess.py的源码，可能导致别的东西因为源码问题不能运行，例如pip install 
```
ERROR: Exception:
Traceback (most recent call last):
File "D:\soft\python3.11.4\Lib\site-packages\pip_internal\cli\base_command.py", line 179, in exc_logging_wrapper
status = run_func(*args)
^^^^^^^^^^^^^^^
File "D:\soft\python3.11.4\Lib\site-packages\pip_internal\cli\req_command.py", line 67, in wrapper
return func(self, options, args)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\soft\python3.11.4\Lib\site-packages\pip_internal\commands\install.py", line 324, in run
session = self.get_default_session(options)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\soft\python3.11.4\Lib\site-packages\pip_internal\cli\index_command.py", line 71, in get_default_session
self._session = self.enter_context(self._build_session(options))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\soft\python3.11.4\Lib\site-packages\pip_internal\cli\index_command.py", line 100, in _build_session
session = PipSession(
^^^^^^^^^^^
File "D:\soft\python3.11.4\Lib\site-packages\pip_internal\network\session.py", line 344, in init
self.headers["User-Agent"] = user_agent()
^^^^^^^^^^^^
File "D:\soft\python3.11.4\Lib\site-packages\pip_internal\network\session.py", line 190, in user_agent
if rustc_output.startswith(b"rustc "):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: startswith first arg must be str or a tuple of str, not bytes
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in run_code
File "D:\soft\python3.11.4\Scripts\pip.exe_main.py", line 7, in <module>
File "D:\soft\python3.11.4\Lib\site-packages\pip_internal\cli\main.py", line 80, in main
return command.main(cmd_args)
^^^^^^^^^^^^^^^^^^^^^^
File "D:\soft\python3.11.4\Lib\site-packages\pip_internal\cli\base_command.py", line 100, in main
return self._main(args)
^^^^^^^^^^^^^^^^
File "D:\soft\python3.11.4\Lib\site-packages\pip_internal\cli\base_command.py", line 234, in _main
self.handle_pip_version_check(options)
File "D:\soft\python3.11.4\Lib\site-packages\pip_internal\cli\index_command.py", line 161, in handle_pip_version_check
session = self._build_session(
^^^^^^^^^^^^^^^^^^^^
File "D:\soft\python3.11.4\Lib\site-packages\pip_internal\cli\index_command.py", line 100, in _build_session
session = PipSession(
^^^^^^^^^^^
File "D:\soft\python3.11.4\Lib\site-packages\pip_internal\network\session.py", line 344, in init
self.headers["User-Agent"] = user_agent()
^^^^^^^^^^^^
File "D:\soft\python3.11.4\Lib\site-packages\pip_internal\network\session.py", line 190, in user_agent
if rustc_output.startswith(b"rustc "):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: startswith first arg must be str or a tuple of str, not bytes
```
你的情况是需要在一个特定的函数中设置 `encoding='utf-8'` 来解决编码问题，但修改全局的 `subprocess` 模块会导致其他问题。可以尝试通过局部解决方案来避免修改全局模块。

一个推荐的办法是利用 `contextlib` 和 `patch` 方法来临时修改 `subprocess.Popen` 的行为。这样可以在你需要的地方修改编码，而不影响全局环境。

下面是一个解决方案：

1. **创建一个上下文管理器**，临时修改 `subprocess.Popen` 的行为：
   
```python
import subprocess
from contextlib import contextmanager
from unittest.mock import patch

@contextmanager
def patched_popen_encoding(encoding='utf-8'):
    original_popen_init = subprocess.Popen.__init__

    def new_popen_init(self, *args, **kwargs):
        kwargs['encoding'] = encoding
        original_popen_init(self, *args, **kwargs)

    with patch.object(subprocess.Popen, '__init__', new_popen_init):
        yield

# Example usage within the context manager
def generateSignature(wss, script_file='sign.js'):
    params = ("live_id,aid,version_code,webcast_sdk_version,"
              "room_id,sub_room_id,sub_channel_id,did_rule,"
              "user_unique_id,device_platform,device_type,ac,"
              "identity").split(',')
    wss_params = urlparse(wss).query.split('&')
    wss_maps = {i.split('=')[0]: i.split("=")[-1] for i in wss_params}
    tpl_params = [f"{i}={wss_maps.get(i, '')}" for i in params]
    param = ','.join(tpl_params)
    md5 = hashlib.md5()
    md5.update(param.encode())
    md5_param = md5.hexdigest()

    with codecs.open(script_file, 'r', encoding='utf-8') as f:
        script = f.read()

    context = execjs.compile(script)
    with patched_popen_encoding(encoding='utf-8'):
        ret = context.call('getSign', {'X-MS-STUB': md5_param})
    return ret.get('X-Bogus')
```

在这个例子中，`patched_popen_encoding` 是一个上下文管理器，它临时修改了 `subprocess.Popen` 的 `__init__` 方法，使其默认使用 `utf-8` 编码。这样，你可以在需要的地方使用这个上下文管理器，而不需要修改全局的 `subprocess` 模块。

2. **使用上下文管理器** 运行你的函数：

```python
# 调用generateSignature函数
wss = 'your_wss_string_here'
result = generateSignature(wss)
print(result)
```

通过这种方法，你可以在特定的地方临时修改 `subprocess` 的行为，避免全局修改带来的副作用。这样既能解决你的编码问题，又不会影响 `pip` 等其他工具的正常运行。
