### ISSUE TITLE
sign.js里面是否修改了

### ISSUE THREAD

**Issue by f-lw** [saermart/DouyinLiveWebFetcher#54]
我把电脑上的js文件同样拷贝了下来，环境也照你的配置的。但是你的X-Bogus跑出来就能用我的用不了，请问除了window._0x5c2014是否还做了其他的修改

**Comment by saermart** [comment]
详见 issue#50

**Comment by saermart** [comment]
- https://github.com/saermart/DouyinLiveWebFetcher/issues/50

**Comment by f-lw** [comment]
> * [关于签名参数的阶段性更新 #50](https://github.com/saermart/DouyinLiveWebFetcher/issues/50)

已经可以了，感谢
