### ISSUE TITLE
ws无法连接

### ISSUE THREAD

**Issue by xlei666** [saermart/DouyinLiveWebFetcher#55]
以下是详细信息：
WebSocket error:  Handshake status 200 OK -+-+- {'server': 'volc-dcdn', 'content-length': '0', 'connection': 'keep-alive', 'date': 'Thu, 25 Jul 2024 10:00:54 GMT', 'handshake-msg': 'DEVICE_BLOCKED', 'handshake-status': '415', 'server-timing': 'inner; dur=44, cdn-cache;desc=MISS,  origin;dur=132, edge;dur=24,  cdn-cache;desc=MISS', 'x-tt-trace-host': '014a4d9192db787a53e7516320b2e00f295d3123a10fb0f54e5f2ba8568bb964d7fa52c0331cdd2f51c3cf896d2f7158334c7141f3aa335d5f3e6834fcbabaa8ac28e7e9dde5f9a69dd3853258fa3254b5dd635a88d1ca89f6ff4655e1fad5ee2e39f6f2daa261a572c1ca30e1fd0c3fae', 'x-tt-trace-tag': 'id=5', 'x-tt-trace-id': '00-e956223f03010bf17be589058b7818ef-e956223f03010bf1-01', 'x-tt-logid': '202407251800546E4D617E90D7B4AA5370', 'via': 'n157-118-098.cqmp.Creative,n123-006-122-157.hnzzcu08-container.Creative', 'x-request-ip': '182.123.***.***', 'x-dsa-trace-id': '172190165488a094c87e0a0b0f397d7f916a1dcb32', 'x-dsa-origin-status': '200'} -+-+- b''
WebSocket connection closed.

**Comment by saermart** [comment]
详见 issue #51
https://github.com/saermart/DouyinLiveWebFetcher/issues/51

**Comment by xlei666** [comment]
更换node版本为18.20/18.2版本后均无效，其中报错'handshake-msg': 'DEVICE_BLOCKED'设备锁定，网页版可以正常打开。

**Comment by saermart** [comment]
可能是你设备原因，我测试都是可以的

**Comment by gaosiming** [comment]
我也是报同样错误，用nvm把node版本从20的LTS，降到18LTS后就可以了。
