### ISSUE TITLE
调用几次就废了，提个建议，可以在获取cookie的位置弹出窗口打开抖音直播页面，然后由人工扫码登录以后获取到Cookie

### ISSUE THREAD

**Issue by leriocn** [saermart/DouyinLiveWebFetcher#6]
【X】Request the live url error:  HTTPSConnectionPool(host='live.douyin.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
【X】Request the live room url error:  HTTPSConnectionPool(host='live.douyin.com', port=443): Max retries exceeded with url: /878471479841 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
【X】Request the live url error:  HTTPSConnectionPool(host='live.douyin.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
【X】Request the live room url error:  HTTPSConnectionPool(host='live.douyin.com', port=443): Max retries exceeded with url: /878471479841 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
【X】Request the live url error:  HTTPSConnectionPool(host='live.douyin.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
【X】Request the live room url error:  HTTPSConnectionPool(host='live.douyin.com', port=443): Max retries exceeded with url: /878471479841 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
【X】Request the live url error:  HTTPSConnectionPool(host='live.douyin.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
【X】Request the live room url error:  HTTPSConnectionPool(host='live.douyin.com', port=443): Max retries exceeded with url: /878471479841 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
【X】Request the live url error:  HTTPSConnectionPool(host='live.douyin.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
WebSocket error:  Handshake status 502 Bad Gateway -+-+- {'server': 'Tengine', 'content-type': 'text/html', 'content-length': '550', 'connection': 'keep-alive', 'date': 'Sun, 18 Feb 2024 08:40:52 GMT', 'proxy-status': '0000201502301102', 'x-tt-trace-host': '0111df544d7f71817403aab46f317c3546cde959325b16508359e5cdf0b8791756437b8a0b7319d471f85a93f642d0f8906a6e9b1a327f3a0c683f595ad15cce94', 'x-tt-trace-tag': 'id=03;cdn-cache=miss;type=dyn', 'x-tt-trace-id': '00-240218164052FEEC55BB30F0B2A703A7-48D3C66468F664CE-00', 'x-tt-logid': '20240218164052FEEC55BB30F0B2A703A7', 'x-alicdn-da-ups-status': 'endOs,0,502', 'via': 'ens-cache21.cn6725[87,0]', 'timing-allow-origin': '*', 'eagleid': '1bde141917082456519776383e'} -+-+- b'<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>TLB</center>\r\n</body>\r\n</html>\r\n\r\n\r\n\r\n\r\n\r\n\r\n'
WebSocket error:  DouyinLiveWebFetcher._wsOnClose() takes 2 positional arguments but 4 were given

**Comment by saermart** [comment]
嗯嗯，加上自己的登录 cookie 获取会更加稳定，也可以通过加代理的方式抓取
