### ISSUE TITLE
request错误

### ISSUE THREAD

**Issue by hcx-good** [saermart/DouyinLiveWebFetcher#61]
D:\anaconda3\env\python310\python.exe D:\Desktop\code\DouyinLiveWebFetcher-main\main.py 
【X】Request the live url error:  HTTPSConnectionPool(host='live.douyin.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021997FCCA70>: Failed to resolve 'live.douyin.com' ([Errno 11001] getaddrinfo failed)"))
【X】Request the live room url error:  HTTPSConnectionPool(host='live.douyin.com', port=443): Max retries exceeded with url: /976589338688 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021997FCCAD0>: Failed to resolve 'live.douyin.com' ([Errno 11001] getaddrinfo failed)"))
【X】Request the live url error:  HTTPSConnectionPool(host='live.douyin.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021997FCD370>: Failed to resolve 'live.douyin.com' ([Errno 11001] getaddrinfo failed)"))
【X】Request the live room url error:  HTTPSConnectionPool(host='live.douyin.com', port=443): Max retries exceeded with url: /976589338688 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021997FCDD00>: Failed to resolve 'live.douyin.com' ([Errno 11001] getaddrinfo failed)"))
【X】Request the live url error:  HTTPSConnectionPool(host='live.douyin.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021997FCDF40>: Failed to resolve 'live.douyin.com' ([Errno 11001] getaddrinfo failed)"))
WebSocket error:  Handshake status 502 Bad Gateway -+-+- {'server': 'volc-dcdn', 'content-type': 'text/html', 'content-length': '550', 'connection': 'keep-alive', 'date': 'Tue, 20 Aug 2024 14:46:37 GMT', 'proxy-status': '0000201502301102', 'x-tt-trace-host': '018e88ccd24af36ef26fac6565de1a05395a4bdad7a16bf62120bf925f5185a1f1d1d54db000f9fe7d49d4f35a652b0921e0d6db5d4c65a6f9956d183bd68ced4d0ae8987d67537880ff58c6abcc29fc8c', 'x-tt-trace-tag': 'id=5', 'x-tt-trace-id': '00-7041100c03010fe2527eaa77028818ef-7041100c03010fe2-01', 'x-tt-logid': '202408202246374BE425A112FB2BB65C83', 'via': 'n157-114-225.cqmp.Creative,n117-187-040-114.gzqxncm01-container.Creative', 'x-request-ip': '117.188.70.159', 'x-dsa-trace-id': '1724165197ae13989903a79b97e4efa2a55c114d33', 'x-dsa-origin-status': '502', 'server-timing': 'cdn-cache;desc=MISS,  origin;dur=89, edge;dur=15, cdn-cache;desc=MISS'} -+-+- b'<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>TLB</center>\r\n</body>\r\n</html>\r\n\r\n\r\n\r\n\r\n\r\n\r\n'
WebSocket connection closed.

**Comment by saermart** [comment]
https://zhuanlan.zhihu.com/p/37508470
