### ISSUE TITLE
一段时间没有消息ws会断开

### ISSUE THREAD

**Issue by mjgaga** [saermart/DouyinLiveWebFetcher#65]
连上后，如果一段时间没有消息（约二三十秒钟），就断开了。
如下：

【直播间统计msg】0在线观众
【直播间排行榜msg】[]
WebSocket error:  Connection to remote host was lost.
WebSocket connection closed.

进程已结束，退出代码为 0

**Comment by saermart** [comment]
可以自己加个重连的逻辑
