### ISSUE TITLE
在我运行的时候，出现了一个参数数量不对的问题，我只是修改了main.py上面的直播间的live_id

### ISSUE THREAD

**Issue by muchenlou** [saermart/DouyinLiveWebFetcher#7]
WebSocket error:  [WinError 10054] 远程主机强迫关闭了一个现有的连接。
WebSocket error:  _wsOnClose() takes 2 positional arguments but 4 were given

![image](https://github.com/saermart/DouyinLiveWebFetcher/assets/29274677/d2761789-0cf2-4978-98e1-c1ffdaa4c8f5)

**Comment by muchenlou** [comment]
或者能否在readme,md 上面 提供一份操作指引 @saermart

**Comment by saermart** [comment]
可以看我代码注释哈，你可能直播间 id 错了

**Comment by muchenlou** [comment]
刚刚又运行了一下，好像又可以了。哈哈哈，大佬牛逼  @saermart
