### ISSUE TITLE
SyntaxError: Unexpected token ?

### ISSUE THREAD

**Issue by zgmd** [saermart/DouyinLiveWebFetcher#70]
![image](https://github.com/user-attachments/assets/8916a8bf-9743-42c1-9790-8fe7797ba2e7)
node 版本是
![image](https://github.com/user-attachments/assets/2c899771-403b-4c01-8914-e33b5668cda4)
这是什么原因？请问下作者是使用的node那个版本？

**Comment by zgmd** [comment]
node 换为 v18.2.0 也是一样的问题

**Comment by saermart** [comment]
可以参考issue#52
