### ISSUE TITLE
没能建立连接，已经失效了吗

### ISSUE THREAD

**Issue by Next-2-You** [saermart/DouyinLiveWebFetcher#71]
WebSocket error:  SSL not available.
WebSocket connection closed.

**Comment by saermart** [comment]
我测试了下可以。
![image](https://github.com/user-attachments/assets/0fd5e72f-e7e0-4b4e-aa1d-495cdb0768c7)

**Comment by yedakuan** [comment]
> 我测试了下可以。 ![image](https://private-user-images.githubusercontent.com/101391149/379180525-0fd5e72f-e7e0-4b4e-aa1d-495cdb0768c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3MzY2NDQsIm5iZiI6MTcyOTczNjM0NCwicGF0aCI6Ii8xMDEzOTExNDkvMzc5MTgwNTI1LTBmZDVlNzJmLWU3ZTAtNGI0ZS1hYTFkLTQ5NWNkYjA3NjhjNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQwMjE5MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MjYwNTBhNDliMTNiMzk5OTUwOTI3YjVkMmI0ZTZkMWFmZjk2NTYwYzU0Nzc4ZjFlNzVlZjE4Nzc0ZjE3NTEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ax_o7GxsxzRTZZ46r6RcA38LfU2mezgpusyk4792ohA)

我也测试了，没有问题的，一直都很稳定。感谢大佬
