### ISSUE TITLE
更新sign.js，无需node环境

### ISSUE THREAD

**Issue by PPG888** [saermart/DouyinLiveWebFetcher#74]
使用py_mini_racer替换execjs库，内置V8引擎，不需要额外安装JS运行环境，sign.js内容更新webmssdk.es5.js

` pip install py_mini_racer`

![image](https://github.com/user-attachments/assets/9f628d96-f2ff-43a7-aec0-a0f5a10e9383)

[sign.zip](https://github.com/user-attachments/files/17644839/sign.zip)

**Comment by PPG888** [comment]
创建MiniRacer实例，写错了
应该从`ctx = MiniRacer().eval(script)`改成  
```
    ctx = MiniRacer()
    ctx.eval(script)
```

![image](https://github.com/user-attachments/assets/c2245c70-7b2a-40e8-95a2-ed251bf3bb64)

**Comment by Walterxxxx** [comment]
import quickjs

    @staticmethod
    def generate_signature(wss, script_file='sign.js'):
        # 参数和URL解析
        params = ("live_id,aid,version_code,webcast_sdk_version,"
                  "room_id,sub_room_id,sub_channel_id,did_rule,"
                  "user_unique_id,device_platform,device_type,ac,"
                  "identity").split(',')
        wss_params = urllib.parse.urlparse(wss).query.split('&')
        wss_maps = {i.split('=')[0]: i.split("=")[-1] for i in wss_params}
        tpl_params = [f"{i}={wss_maps.get(i, '')}" for i in params]
        param = ','.join(tpl_params)
        md5 = hashlib.md5()
        md5.update(param.encode())
        md5_param = md5.hexdigest()

        # 读取JavaScript文件内容
        with codecs.open(script_file, 'r', encoding='utf8') as f:
            script = f.read()

        # 创建 quickjs 上下文
        ctx = quickjs.Context()
        ctx.eval(script)  # 加载 sign.js 中的代码

        # 定义并调用 get_sign 函数
        try:
            signature = ctx.eval(f'get_sign("{md5_param}")')
            return signature
        except Exception as e:
            print(e)
            
            
用PPG888更新的sign.js, 可以用quickjs替换execjs库，无需node环境

**Comment by largetech** [comment]
错误：windows环境下安装py_mini_racer库 运行报缺失mini_racer
![微信截图_20250113154245](https://github.com/user-attachments/assets/16c31176-3337-4e51-b18d-40f6a611e349)
.ddl 文件。

**Comment by Yawanaika** [comment]
> 错误：windows环境下安装py_mini_racer库运行报装载mini_racer.ddl文件。 ![微信截图_20250113154245](https://private-user-images.githubusercontent.com/44046927/402460931-16c31176-3337-4e51-b18d-40f6a611e349.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY3NTU3MzksIm5iZiI6MTczNjc1NTQzOSwicGF0aCI6Ii80NDA0NjkyNy80MDI0NjA5MzEtMTZjMzExNzYtMzMzNy00ZTUxLWIxOGQtNDBmNmE2MTFlMzQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTEzVDA4MDM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlMTM2NzU1YTM5ZjIxMjlmOTg1MTQ3NmIzYjA5MDYzZTExNjk2MmFkMmE4NzcxZTI3MWMxN2NlNThkMjYwNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7X-QaXNJ-cUfTnapmbB06SI5l9C9MWKRd98GO_aBF9w)


尝试使用py_mini_racer库的升级版本 mini-racer库。
`pip install mini_racer`

**Comment by yxbbing123** [comment]
使用mini-racer 库，打包程序.exe,无法运行，
#
# Fatal error in , line 0
# Failed to deserialize the V8 snapshot blob. This can mean that the snapshot blob file is corrupted or missing.
#FailureMessage Object: 000000D3990EDBA0
