### ISSUE TITLE
现在只能收到两类消息？

### ISSUE THREAD

**Issue by richardguancn** [saermart/DouyinLiveWebFetcher#75]
今天试了下，只能收到WebcastRoomStatsMessage和WebcastLikeMessage两类消息，请问其他的消息为啥收到不到了？

**Comment by saermart** [comment]
刚刚测试了下，还是可以的
![image](https://github.com/user-attachments/assets/2f09a01d-a631-4a50-863a-5f5d4298076f)

**Comment by richardguancn** [comment]
对，我今天测了也可以了。
