### ISSUE TITLE
是否愿意组建群聊？

### ISSUE THREAD

**Issue by HanMinge** [saermart/DouyinLiveWebFetcher#77]
请问作者是否愿意组建群聊，作者一个人更新难免感觉乏累，我愿意为项目做一份共享。

**Comment by saermart** [comment]
> 请问作者是否愿意组建群聊，作者一个人更新难免感觉乏累，我愿意为项目做一份共享。

感谢兄弟的支持:)，主要是项目不是啥正经项目（狗头），所以没有扩大规模的意向😜，有侵权或者其他的不可抗力直接删库跑路哈哈哈哈，还是再次感谢支持！

**Comment by saermart** [comment]
有邮箱和B站链接在主页哈~
