### ISSUE TITLE
连接被断开

### ISSUE THREAD

**Issue by shayushark** [saermart/DouyinLiveWebFetcher#8]
你好，请问我连接上了，服务器不会给我发送任何消息，然后就被断开了，这种情况是不是需要加cookie，具体需要加哪些呢？我带了登录cookie还是会被断开

**Comment by saermart** [comment]
一种情况是你的 ip 请求太频繁被风控了，需要加代理请求；另一种是你的直播间 id 可能错误的。

**Comment by shayushark** [comment]
各个直播间都连不上，看来是风控了。

**Comment by shayushark** [comment]
登录前网页直播间会一直弹窗，且不会拉取弹幕，登陆后正常

**Comment by saermart** [comment]
加上 cookie 可能就好了，但如果还是太频繁还是会被封 ip 或者封号［狗头］
