### ISSUE TITLE
自己直播伴侣开的直播间,人少了每隔半分钟左右就断开连接

### ISSUE THREAD

**Issue by HiramLobato34** [saermart/DouyinLiveWebFetcher#86]
找了别人人少的直播间没发现这个问题,加了代理也不行

WebSocket error:  Connection to remote host was lost.
WebSocket connection closed.

**Comment by saermart** [comment]
> 找了别人人少的直播间没发现这个问题,加了代理也不行
> 
> WebSocket error:  Connection to remote host was lost.
> WebSocket connection closed.


其他人少直播间没发现这个问题？只有自己的直播间这样吗？

**Comment by HiramLobato34** [comment]
对的，但是似乎解决了，我模仿模仿网页端每10秒发送心跳包就没有断开连接了

**Comment by zhouytforever** [comment]
> 对的，但是似乎解决了，我模仿模仿网页端每10秒发送心跳包就没有断开连接了 [@saermart](https://github.com/saermart)

能否给个代码片断，我也学习下
